version: '3'
services:
  zeo:
    build:
      context: .
    image: imiolibrary
    volumes:
      - ./var/blobstorage:/data/blobstorage
      - ./var/filestorage:/data/filestorage
      - ./src:/plone/src
    command: bin/zeoserver fg
    expose:
      - 8100
    healthcheck:
      # test: ["CMD-SHELL", "nc", "-z", "w5", "127.0.0.1", "8100", "||", "exit", "1"]
      test: ["CMD", "nc", "-z", "-w5", "127.0.0.1", "8100"]
  instance:
    image: imiolibrary
    ports:
      - 8080:8080
    links:
      - zeo:db
    depends_on:
      - reverseproxy
    volumes:
      - ./var/blobstorage:/data/blobstorage
      - ./src:/plone/src
    environment:
      - PLONE_EXTENSION_IDS=plone.app.caching:default,plonetheme.barceloneta:default,library.policy:default
      - DEFAULT_LANGUAGE=fr
      - ACTIVE_BIGBANG=True
    command: fg
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.instance.rule=Host(`portal.localhost`)'
      - 'traefik.http.routers.instance.entrypoints=web'
      - 'traefik.http.services.instance.loadbalancer.server.port=8080'
      - "traefik.http.routers.instance.middlewares=add-plone"
      - "traefik.http.middlewares.add-plone.addprefix.prefix=/VirtualHostBase/http/portal.localhost/plone/VirtualHostRoot"

  reverseproxy:
    image: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entryPoints.web.address=:80'
    ports:
      - '80:80' # The HTTP port
      - '8000:8080' # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
