version: '2.4'
volumes:
  library-postgres:
services:
  instance:
    build:
      context: .
    image: imiolibrary
    ports:
      - 8080:8080
    links:
      - postgres:db
    depends_on:
      - postgres
      - reverseproxy
    volumes:
      - ./var/blobstorage:/data/blobstorage
      - ./src:/plone/src
    environment:
      - PLONE_EXTENSION_IDS=plone.app.caching:default,plonetheme.barceloneta:default,library.policy:default
      - DEFAULT_LANGUAGE=fr
      - ACTIVE_BIGBANG=True
      - RELSTORAGE_HOSTNAME=db
      - RELSTORAGE_PORT=5432
      - RELSTORAGE_DB=${RELSTORAGE_DB:-library}
      - RELSTORAGE_USER=${RELSTORAGE_USER:-library}
      - RELSTORAGE_PASSWORD=${RELSTORAGE_PASSWORD}
      - MEMCACHE_SERVER=memcached
      - PROJECT_ID=library
      - ZODB_CACHE_SIZE=30000
      - ZEO_CLIENT_CACHE_SIZE=256MB
    command: fg
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.instance.rule=Host(`portal.localhost`)'
      - 'traefik.http.services.instance.loadbalancer.server.port=8080'
      - "traefik.http.routers.instance.middlewares=add-plone"
      - "traefik.http.middlewares.add-plone.addprefix.prefix=/VirtualHostBase/http/portal.localhost/Plone/VirtualHostRoot"
  postgres:
    image: postgres:17.6
    environment:
      - POSTGRES_DB=${RELSTORAGE_DB:-library}
      - POSTGRES_USER=${RELSTORAGE_USER:-library}
      - POSTGRES_PASSWORD=${RELSTORAGE_PASSWORD}
    volumes:
      - library-postgres:/var/lib/postgresql/data
  memcached:
    image: memcached:1.5.20
    command:
      - "-m"
      - "1024"
  reverseproxy:
    image: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
    ports:
      - '80:80' # The HTTP port
      - '8000:8080' # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
